html anchor tag changed to wiki markdown
a link left in html format broke the build with a very unhelpful message:
Error: Error reading the frontmatter ...